---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 13:36
---
module = {}
-- 定义一个常量
module.constant = "这是一个常量"

-- 定义一个函数
function module.func1()
    io.write("This is public Function")
end

local function fun2()
    print("This is private Function")
end

function module.fun3()
    fun2()
end

return module