---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 13:54
---


function show()
    print("Hello Matthew")
    print(add2(1.0, 2.0))
    print(sub2(20.1, 19))
    print(l_sin(1))
end

show()