---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 11:41
---
-- 初始化数组
array = {}
for i = 1,3 do
    array[i] = {}
    for j = 1, 3 do
        array[i][j] = i*j
    end
end

-- 访问数组
for i = 1, 3 do
    for j = 1, 3 do
        print(array[i][j])
    end
end

