---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 10:55
---

-- 多返回值
-- Lua函数可以返回多个结果值，比如string.find，其返回匹配串"开始和结束的下标"

function maximum(a)
    local mi = 1 -- 最大值索引
    local m = a[mi] --最大值
    for i, v in ipairs(a) do
        if v > m then
            mi = i
            m = v
        end
    end
    return m,mi
end

print(maximum({8,10,23,12,5}))