---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 10:32
---
--[[ 函数返回两个值的最大值 --]]
function max(n1, n2)
    if n1 > n2 then
        result = n1
    else
        result = n2
    end

    return result
end

-- 调用函数
print("两值比较最大值为 ",max(10,4))
print("两值比较最大值为 ",max(5,6))