---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 10:47
---
myPrint = function(param)
    print("这是打印函数 - ##", param, "##")
end

function add(n1, n2, functionPrint)
    result = n1 + n2
    -- 调用传递的函数参数
    functionPrint(result)
end

myPrint(10)

-- myprint 函数作为参数传递
add(2,5, myPrint)