---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 10:52
---

function average(...)
    result = 0
    local arg={...}
    for i,v in ipairs(arg) do
        result = result + v
    end
    print("总共传入" .. #arg .. "个数")
    return result/#arg
end

print("平均值为", average(10, 4, 4,3, 5, 6))