package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ade/jenkins/workspace/8-2-build-owindows-i586-cygwin/jdk8u41/500/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, January 15, 2020 7:02:48 AM UTC
*/

public interface TAG_CODE_SETS
{

  /**
     * The code set component of the IOR multi-component profile structure
     * contains:
     * <ul>
     *   <li>server's native char code set and conversion code sets, and</li>
     *   <li>server's native wchar code set and conversion code sets.</li>
     * </ul>
     * Both char and wchar conversion code sets are listed in order of 
     * preference.
     */
  public static final int value = (int)(1L);
}
