---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 13:23
---

fruits = {"banana","orange","apple"}
-- 返回 table 连接后的字符串
print("连接后的字符串 ",table.concat(fruits))

-- 指定连接字符
print("连接后的字符串", table.concat(fruits, ","))

-- 指定索引来连接 table
print("连接后的字符串", table.concat(fruits,", ", 2, 3))