---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 12:02
---
--[[
Lua table 是不固定大小的，你可以根据自己需要进行扩容。

Lua也是通过table来解决模块（module）、包（package）和对象（Object）的。 例如string.format表示使用"format"来索引table string。]]


-- 简单的 table
my_table = {}
print("my_table 的类型是 ",type(my_table))

my_table[1] ="Lua"
my_table["Wow"] = "修改前"
print("my_table 索引为 1 的元素是 ", my_table[1])
print("my_table 索引为 wow 的元素是 ", my_table["Wow"])

-- alternatetable和mytable的是指同一个 table
alternatetable = my_table
print("alternatetable 索引为 1 的元素是 ", alternatetable[1])
print("my_table 索引为 wow 的元素是 ", alternatetable["Wow"])


alternatetable["Wow"] = "修改后"
print("my_table 索引为 wow 的元素是 ", my_table["Wow"])

-- 释放变量
alternatetable = nil
print("alternatetable 是", alternatetable)

-- mytable 仍然可以访问
print("mytable 索引为 Wow 的元素是", my_table["Wow"])

my_table = nil
print("mytable 是 ", my_table)