---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 10:01
---

-- Meta class
--[[
Shape  = {area = 0, length = 0, breadth = 0}

-- 基础类方法 new
function Shape :new(o , length, breadth)
    o = o or {}
    setmetatable(o ,self)
    self._index = self
    self.length = length or 0
    self.breadth = breadth or 0
    self.area = length*breadth;
    return o
end

-- 派生类的方法 printArea
function Shape :printArea()
    print("矩形面积为", self.area)
end

-- 创建对象
myShape = Shape:new(nil, 10, 10)

myShape:printArea()]]
