---
--- Generated by Luanalysis
--- Created by Admin.
--- DateTime: 2021/8/13 10:15
---
-- Meta class
Shape = {area = 0}

-- 基础类方法 new
function Shape:new (o,side)
    o = o or {}
    set-metatable(o, self)
    self._index = self
    side = side or 0
    self.area = side*side;
    return o
end

-- 基础类方法 printArea
function Shape:printArea ()
    print("面积为 ",self.area)
end

-- 创建对象
shape = Shape:new(nil,10)

shape:printArea()